<a href="https://colab.research.google.com/github/yanamushka/ML-course/blob/main/hw_2_3_ipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [ ]:
import numpy as np
vector = np.random.rand(10)
print(vector)
print(f"Розмір вектора: {vector.shape}")

[0.97671295 0.5613916  0.47258373 0.60953335 0.40025109 0.22010123
 0.44249867 0.53341179 0.17183856 0.73359193]
Розмір вектора: (10,)


In [ ]:
matrix = np.array([[11,14,17], [20, 23, 26], [29, 32, 35]])
print(matrix)
print(f"Розмір матриці: {matrix.shape}")

[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розмір матриці: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [ ]:
vector_10 = np.round(np.dot(10,vector), 2)
vector_10

array([9.77, 5.61, 4.73, 6.1 , 4.  , 2.2 , 4.42, 5.33, 1.72, 7.34])

In [ ]:
matrix_2 = 2*matrix
matrix_2

array([[22, 28, 34],
       [40, 46, 52],
       [58, 64, 70]])

In [ ]:
vector_2 = vector**2
vector_2

array([0.95396818, 0.31516053, 0.22333539, 0.3715309 , 0.16020094,
       0.04844455, 0.19580508, 0.28452813, 0.02952849, 0.53815711])


### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [ ]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

Щоб отримати матрицю розмірністю 2 на 2 множимо матрицю, яка має 2 рядки на матрицю яка має 2 стовпці

In [ ]:
result_matrix = np.dot(B, A)
result_matrix

array([[0.7281, 0.5202],
       [0.2034, 0.2846]])

Матриця С має 2 рядки та 1 стовпчик, тому якщо домножуємо результуючу матрицю на С отримуємо розмірність 2 на 1

In [ ]:
np.dot( result_matrix, C)

array([[0.5202],
       [0.2846]])

In [ ]:
np.dot(result_matrix, D)

array([[0.5202, 0.7281],
       [0.2846, 0.2034]])


### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [ ]:
np.linalg.det(result_matrix)


0.10140857999999997

детермінант більше 0, тому матриця не вироджена

In [ ]:
result_matrix.T

array([[0.7281, 0.2034],
       [0.5202, 0.2846]])

In [ ]:
vector_transp = vector.T
vector_transp.shape


(10,)

In [ ]:
vector

array([0.97671295, 0.5613916 , 0.47258373, 0.60953335, 0.40025109,
       0.22010123, 0.44249867, 0.53341179, 0.17183856, 0.73359193])

In [ ]:
vector_transp

array([0.6906254 , 0.45795382, 0.66512032, 0.88495982, 0.94715309,
       0.19033313, 0.68752672, 0.17883191, 0.59423368, 0.74122831])

Транспонований вектор не відрізняється від початкового, так як це одновимірний масив і в результаті після використання методу .Т отримуємо той же масив

In [ ]:
column_vector = np.expand_dims(vector, axis = 1)
column_vector

array([[0.97671295],
       [0.5613916 ],
       [0.47258373],
       [0.60953335],
       [0.40025109],
       [0.22010123],
       [0.44249867],
       [0.53341179],
       [0.17183856],
       [0.73359193]])

Column_vector відрізняється від транспонованого вектора візуально

In [ ]:
column_vector.T

array([[0.97671295, 0.5613916 , 0.47258373, 0.60953335, 0.40025109,
        0.22010123, 0.44249867, 0.53341179, 0.17183856, 0.73359193]])

In [ ]:
column_vector.shape

(10, 1)

Розмірність column_vector - (10, 1) в той час як розмірність vector (10, )